export const AuthTypes = {
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  SET_ERROR: 'SET_ERROR',
  SET_ERRORS: 'SET_ERRORS',
  SET_AUTH_LOADING: 'SET_AUTH_LOADING',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  LOGOUT: 'LOGOUT',
};
