export const DataTypes = {
  SET_USER_DATA: 'SET_USER_DATA',
  REMOVE_USER_DATA_FIELD: 'REMOVE_USER_DATA_FIELD',
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  SET_MESSAGE: 'SET_MESSAGE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
  SET_LOADING: 'SET_LOADING',
};
